/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.surviveRexburg.frames;

import Survivrexburg.SurviveRexburg;
import byui.cit260.survivRexburg.control.FrameSceneControl;
import byui.cit260.survivRexburg.control.MapControl;

/**
 *
 * @author arturoaguila
 */
public class Map2Frame extends javax.swing.JFrame {

    String currentLocation = SurviveRexburg.getEndUser().getEndUserLocation().getName();
    
    
    
    /**
     * Creates new form Map2Frame
     */
    public Map2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GunStoreButton = new javax.swing.JButton();
        JambaJuiceButton = new javax.swing.JButton();
        BroulimsButton = new javax.swing.JButton();
        FireDeptButton = new javax.swing.JButton();
        TacoBellButton = new javax.swing.JButton();
        BikeStoreButton = new javax.swing.JButton();
        InsuranceButton = new javax.swing.JButton();
        MaverikButton = new javax.swing.JButton();
        DominosButton = new javax.swing.JButton();
        SalonButton = new javax.swing.JButton();
        MelaleucaButton = new javax.swing.JButton();
        DonutsButton = new javax.swing.JButton();
        GringosButton = new javax.swing.JButton();
        KeyBankButton = new javax.swing.JButton();
        PorterParkFieldButton = new javax.swing.JButton();
        PorterParkPlaygroundButton = new javax.swing.JButton();
        NielsensButton = new javax.swing.JButton();
        AbandonedHouseOneButton = new javax.swing.JButton();
        LaJollaButton = new javax.swing.JButton();
        LittleCeasersButton = new javax.swing.JButton();
        EyeDoctorButton = new javax.swing.JButton();
        PinnacleButton = new javax.swing.JButton();
        KiwiLocoButton = new javax.swing.JButton();
        WillowsButton = new javax.swing.JButton();
        ConstructionButton = new javax.swing.JButton();
        PostOfficeButton = new javax.swing.JButton();
        VikingVillageButton = new javax.swing.JButton();
        EmptyLotButton = new javax.swing.JButton();
        TacoTimeButton = new javax.swing.JButton();
        BirchwoodWestButton = new javax.swing.JButton();
        BirchwoodEastButton = new javax.swing.JButton();
        StadiumButton = new javax.swing.JButton();
        SnowBuildingButton = new javax.swing.JButton();
        EmptyFieldButton = new javax.swing.JButton();
        AbandonedHouseTwoButton = new javax.swing.JButton();
        NewFongsButton = new javax.swing.JButton();
        KirkhamButton = new javax.swing.JButton();
        RoyalCrestButton = new javax.swing.JButton();
        BrooklynButton = new javax.swing.JButton();
        CrestwoodButton = new javax.swing.JButton();
        AlleywayButton = new javax.swing.JButton();
        BunkhouseButton = new javax.swing.JButton();
        LibraryButton = new javax.swing.JButton();
        SmithBuildingButton = new javax.swing.JButton();
        ClarkeBuildingButton = new javax.swing.JButton();
        HartBuildingButton = new javax.swing.JButton();
        SporiBuildingButton = new javax.swing.JButton();
        AbandonedHouseThreeButton = new javax.swing.JButton();
        TacoBusButton = new javax.swing.JButton();
        SubwayButton = new javax.swing.JButton();
        ShakeOutButton = new javax.swing.JButton();
        ICenterButton = new javax.swing.JButton();
        MCWestButton = new javax.swing.JButton();
        MCEastButton = new javax.swing.JButton();
        NorthDormsButton = new javax.swing.JButton();
        SouthButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ExitMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("28 Days Later", 0, 48)); // NOI18N
        jLabel1.setText("Map");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        GunStoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/GunStoreLogo.png"))); // NOI18N
        GunStoreButton.setSize(new java.awt.Dimension(20, 20));
        GunStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GunStoreButtonActionPerformed(evt);
            }
        });

        JambaJuiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/JambaJuiceLogo.gif"))); // NOI18N
        JambaJuiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JambaJuiceButtonActionPerformed(evt);
            }
        });

        BroulimsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BroulimsLogo.png"))); // NOI18N
        BroulimsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroulimsButtonActionPerformed(evt);
            }
        });

        FireDeptButton.setBackground(new java.awt.Color(255, 255, 255));
        FireDeptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/FireStationLogo.jpg"))); // NOI18N
        FireDeptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FireDeptButtonActionPerformed(evt);
            }
        });

        TacoBellButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/TacoBellLogo.jpg"))); // NOI18N
        TacoBellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TacoBellButtonActionPerformed(evt);
            }
        });

        BikeStoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BikeStoreLogo.jpg"))); // NOI18N
        BikeStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeStoreButtonActionPerformed(evt);
            }
        });

        InsuranceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/InsuranceLogo.jpg"))); // NOI18N
        InsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceButtonActionPerformed(evt);
            }
        });

        MaverikButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/MavericksLogo.png"))); // NOI18N
        MaverikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaverikButtonActionPerformed(evt);
            }
        });

        DominosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/DominosLogo.jpeg"))); // NOI18N
        DominosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DominosButtonActionPerformed(evt);
            }
        });

        SalonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/SalonLogo.png"))); // NOI18N
        SalonButton.setToolTipText("");
        SalonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalonButtonActionPerformed(evt);
            }
        });

        MelaleucaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/MelaleucaLogo.jpg"))); // NOI18N
        MelaleucaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MelaleucaButtonActionPerformed(evt);
            }
        });

        DonutsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/DonutsLogo.png"))); // NOI18N
        DonutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonutsButtonActionPerformed(evt);
            }
        });

        GringosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/GringosLogo.jpg"))); // NOI18N
        GringosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GringosButtonActionPerformed(evt);
            }
        });

        KeyBankButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/KeybankLogo.gif"))); // NOI18N
        KeyBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyBankButtonActionPerformed(evt);
            }
        });

        PorterParkFieldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/PorterParkField.JPG"))); // NOI18N
        PorterParkFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorterParkFieldButtonActionPerformed(evt);
            }
        });

        PorterParkPlaygroundButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/PorterParkPlaygroundLogo.JPG"))); // NOI18N
        PorterParkPlaygroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorterParkPlaygroundButtonActionPerformed(evt);
            }
        });

        NielsensButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/NielsensLogo.png"))); // NOI18N
        NielsensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NielsensButtonActionPerformed(evt);
            }
        });

        AbandonedHouseOneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/AbandonedHouseLogo.jpeg"))); // NOI18N
        AbandonedHouseOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbandonedHouseOneButtonActionPerformed(evt);
            }
        });

        LaJollaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/LaJollaLogo.jpg"))); // NOI18N
        LaJollaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaJollaButtonActionPerformed(evt);
            }
        });

        LittleCeasersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/LittleCeasersLogo.jpg"))); // NOI18N
        LittleCeasersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LittleCeasersButtonActionPerformed(evt);
            }
        });

        EyeDoctorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/EyeDoctorLogo.png"))); // NOI18N
        EyeDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeDoctorButtonActionPerformed(evt);
            }
        });

        PinnacleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/PinnacleLogo.png"))); // NOI18N
        PinnacleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinnacleButtonActionPerformed(evt);
            }
        });

        KiwiLocoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/KiwiLocoLogo.png"))); // NOI18N
        KiwiLocoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiwiLocoButtonActionPerformed(evt);
            }
        });

        WillowsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/WillowsLogo.png"))); // NOI18N
        WillowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WillowsButtonActionPerformed(evt);
            }
        });

        ConstructionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/ConstructionLogo.jpg"))); // NOI18N
        ConstructionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstructionButtonActionPerformed(evt);
            }
        });

        PostOfficeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/PostOfficeLogo.jpg"))); // NOI18N
        PostOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostOfficeButtonActionPerformed(evt);
            }
        });

        VikingVillageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/VikingVillageLogo.jpeg"))); // NOI18N
        VikingVillageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VikingVillageButtonActionPerformed(evt);
            }
        });

        EmptyLotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/EmptyLotLogo.jpg"))); // NOI18N
        EmptyLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmptyLotButtonActionPerformed(evt);
            }
        });

        TacoTimeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/TacoTimeLogo.gif"))); // NOI18N
        TacoTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TacoTimeButtonActionPerformed(evt);
            }
        });

        BirchwoodWestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BirchwoodLogo.jpg"))); // NOI18N
        BirchwoodWestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirchwoodWestButtonActionPerformed(evt);
            }
        });

        BirchwoodEastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BirchwoodLogo.jpg"))); // NOI18N
        BirchwoodEastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirchwoodEastButtonActionPerformed(evt);
            }
        });

        StadiumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/StadiumLogo.jpg"))); // NOI18N
        StadiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StadiumButtonActionPerformed(evt);
            }
        });

        SnowBuildingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/SnowBuildingLogo.png"))); // NOI18N
        SnowBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnowBuildingButtonActionPerformed(evt);
            }
        });

        EmptyFieldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/EmptyLotLogo.jpg"))); // NOI18N
        EmptyFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmptyFieldButtonActionPerformed(evt);
            }
        });

        AbandonedHouseTwoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/AbandonedHouseLogo.jpeg"))); // NOI18N
        AbandonedHouseTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbandonedHouseTwoButtonActionPerformed(evt);
            }
        });

        NewFongsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/NewFongsLogo.jpg"))); // NOI18N
        NewFongsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFongsButtonActionPerformed(evt);
            }
        });

        KirkhamButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/KirkhamBuildingLogo.jpg"))); // NOI18N
        KirkhamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirkhamButtonActionPerformed(evt);
            }
        });

        RoyalCrestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/RoyalCrestLogo.jpg"))); // NOI18N
        RoyalCrestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoyalCrestButtonActionPerformed(evt);
            }
        });

        BrooklynButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BrooklynLogo.png"))); // NOI18N
        BrooklynButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrooklynButtonActionPerformed(evt);
            }
        });

        CrestwoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/CrestwoodLogo.png"))); // NOI18N
        CrestwoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrestwoodButtonActionPerformed(evt);
            }
        });

        AlleywayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/AlleywayLogo.png"))); // NOI18N
        AlleywayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlleywayButtonActionPerformed(evt);
            }
        });

        BunkhouseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/BunkhouseLogo.png"))); // NOI18N
        BunkhouseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BunkhouseButtonActionPerformed(evt);
            }
        });

        LibraryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/LibraryLogo.png"))); // NOI18N
        LibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryButtonActionPerformed(evt);
            }
        });

        SmithBuildingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/SmithBuildingLogo.png"))); // NOI18N
        SmithBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmithBuildingButtonActionPerformed(evt);
            }
        });

        ClarkeBuildingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/ClarkeBuildingLogo.png"))); // NOI18N
        ClarkeBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClarkeBuildingButtonActionPerformed(evt);
            }
        });

        HartBuildingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/HartBuildingLogo.jpg"))); // NOI18N
        HartBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HartBuildingButtonActionPerformed(evt);
            }
        });

        SporiBuildingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/SporiBuildingLogo.png"))); // NOI18N
        SporiBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SporiBuildingButtonActionPerformed(evt);
            }
        });

        AbandonedHouseThreeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/AbandonedHouseLogo.jpeg"))); // NOI18N
        AbandonedHouseThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbandonedHouseThreeButtonActionPerformed(evt);
            }
        });

        TacoBusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/TacoBusLogo.JPG"))); // NOI18N
        TacoBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TacoBusButtonActionPerformed(evt);
            }
        });

        SubwayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/SubwayLogo.gif"))); // NOI18N
        SubwayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubwayButtonActionPerformed(evt);
            }
        });

        ShakeOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/ShakeOutLogo.jpg"))); // NOI18N
        ShakeOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShakeOutButtonActionPerformed(evt);
            }
        });

        ICenterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/ICenterLogo.jpg"))); // NOI18N
        ICenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICenterButtonActionPerformed(evt);
            }
        });

        MCWestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/MCWestLogo.png"))); // NOI18N
        MCWestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCWestButtonActionPerformed(evt);
            }
        });

        MCEastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/MCEastLogog.png"))); // NOI18N
        MCEastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCEastButtonActionPerformed(evt);
            }
        });

        NorthDormsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/DormsLogo.jpg"))); // NOI18N
        NorthDormsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthDormsButtonActionPerformed(evt);
            }
        });

        SouthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/surviveRexburg/images/DormsLogo.jpg"))); // NOI18N
        SouthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GunStoreButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JambaJuiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BroulimsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FireDeptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TacoBellButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BikeStoreButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsuranceButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MaverikButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DominosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MelaleucaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DonutsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GringosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KeyBankButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PorterParkFieldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NielsensButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbandonedHouseOneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LaJollaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LittleCeasersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EyeDoctorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PinnacleButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PorterParkPlaygroundButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KiwiLocoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WillowsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConstructionButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TacoTimeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirchwoodWestButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirchwoodEastButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StadiumButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SnowBuildingButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KirkhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CrestwoodButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PostOfficeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VikingVillageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmptyLotButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EmptyFieldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbandonedHouseTwoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoyalCrestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HartBuildingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SporiBuildingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClarkeBuildingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbandonedHouseThreeButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NewFongsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BrooklynButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BunkhouseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlleywayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LibraryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SmithBuildingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NorthDormsButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TacoBusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubwayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShakeOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ICenterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MCWestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MCEastButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SouthButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsuranceButton)
                    .addComponent(BikeStoreButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GunStoreButton)
                        .addComponent(JambaJuiceButton)
                        .addComponent(BroulimsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FireDeptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TacoBellButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaverikButton)
                    .addComponent(DominosButton)
                    .addComponent(SalonButton)
                    .addComponent(MelaleucaButton)
                    .addComponent(DonutsButton)
                    .addComponent(GringosButton)
                    .addComponent(KeyBankButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NielsensButton)
                    .addComponent(PorterParkFieldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AbandonedHouseOneButton)
                    .addComponent(LaJollaButton)
                    .addComponent(LittleCeasersButton)
                    .addComponent(EyeDoctorButton)
                    .addComponent(PinnacleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KiwiLocoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PorterParkPlaygroundButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WillowsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConstructionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PostOfficeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VikingVillageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyLotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TacoTimeButton)
                    .addComponent(BirchwoodWestButton)
                    .addComponent(BirchwoodEastButton)
                    .addComponent(StadiumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SnowBuildingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KirkhamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrestwoodButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AbandonedHouseTwoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmptyFieldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RoyalCrestButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HartBuildingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SporiBuildingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClarkeBuildingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(AbandonedHouseThreeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewFongsButton)
                    .addComponent(BrooklynButton)
                    .addComponent(BunkhouseButton)
                    .addComponent(AlleywayButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(NorthDormsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SmithBuildingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LibraryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SubwayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TacoBusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ShakeOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ICenterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MCWestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SouthButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MCEastButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setText("Current Location: " + currentLocation);

        ExitMap.setText("Exit");
        ExitMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitMap)
                .addGap(307, 307, 307))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ExitMap)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMapActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMapActionPerformed

    private void GunStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GunStoreButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToGunStore();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_GunStoreButtonActionPerformed

    private void JambaJuiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JambaJuiceButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToJambaJuice();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_JambaJuiceButtonActionPerformed

    private void BroulimsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroulimsButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBroulims();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BroulimsButtonActionPerformed

    private void FireDeptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FireDeptButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToFireStation();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_FireDeptButtonActionPerformed

    private void TacoBellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TacoBellButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToTacoBell();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_TacoBellButtonActionPerformed

    private void BikeStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeStoreButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBikeStore();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BikeStoreButtonActionPerformed

    private void InsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToInsuranceOffice();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_InsuranceButtonActionPerformed

    private void MaverikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaverikButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToMavericks();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_MaverikButtonActionPerformed

    private void DominosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DominosButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToDominos();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_DominosButtonActionPerformed

    private void SalonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalonButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSalon();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SalonButtonActionPerformed

    private void MelaleucaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MelaleucaButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToMelaluca();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_MelaleucaButtonActionPerformed

    private void DonutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonutsButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToDonutStore();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_DonutsButtonActionPerformed

    private void GringosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GringosButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToGringos();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_GringosButtonActionPerformed

    private void KeyBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyBankButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToKeyBank();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_KeyBankButtonActionPerformed

    private void PorterParkFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorterParkFieldButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToPorterParkField();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_PorterParkFieldButtonActionPerformed

    private void PorterParkPlaygroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorterParkPlaygroundButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToPorterParkPlayground();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_PorterParkPlaygroundButtonActionPerformed

    private void NielsensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NielsensButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToNielsons();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_NielsensButtonActionPerformed

    private void AbandonedHouseOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbandonedHouseOneButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToAbandondedHouseOne();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_AbandonedHouseOneButtonActionPerformed

    private void AbandonedHouseTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbandonedHouseTwoButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToAbandondedHouseOne();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_AbandonedHouseTwoButtonActionPerformed

    private void AbandonedHouseThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbandonedHouseThreeButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToAbandondedHouseOne();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_AbandonedHouseThreeButtonActionPerformed

    private void LaJollaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaJollaButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToLaJolla();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_LaJollaButtonActionPerformed

    private void LittleCeasersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LittleCeasersButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToLittleCaesers();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_LittleCeasersButtonActionPerformed

    private void EyeDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EyeDoctorButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToEyeDoctor();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_EyeDoctorButtonActionPerformed

    private void PinnacleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinnacleButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToPinnacleSecurityOffice();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_PinnacleButtonActionPerformed

    private void KiwiLocoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiwiLocoButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToKiwiLoco();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_KiwiLocoButtonActionPerformed

    private void WillowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WillowsButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToWillows();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_WillowsButtonActionPerformed

    private void ConstructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstructionButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToConstruction();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_ConstructionButtonActionPerformed

    private void PostOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostOfficeButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToPostOffice();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_PostOfficeButtonActionPerformed

    private void VikingVillageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VikingVillageButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToVikingVillage();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_VikingVillageButtonActionPerformed

    private void EmptyLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmptyLotButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToEmptyLot();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_EmptyLotButtonActionPerformed

    private void TacoTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TacoTimeButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToTacoTime();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_TacoTimeButtonActionPerformed

    private void BirchwoodWestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirchwoodWestButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBirchwoodWest();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BirchwoodWestButtonActionPerformed

    private void BirchwoodEastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirchwoodEastButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBirchwoodEast();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BirchwoodEastButtonActionPerformed

    private void StadiumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StadiumButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToStadium();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_StadiumButtonActionPerformed

    private void SnowBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnowBuildingButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSnowBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SnowBuildingButtonActionPerformed

    private void KirkhamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirkhamButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToKirkhamBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_KirkhamButtonActionPerformed

    private void CrestwoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrestwoodButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToCrestwood();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_CrestwoodButtonActionPerformed

    private void EmptyFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmptyFieldButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToEmptyField();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_EmptyFieldButtonActionPerformed

    private void RoyalCrestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoyalCrestButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToRoyalCrest();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_RoyalCrestButtonActionPerformed

    private void HartBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HartBuildingButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToHartBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_HartBuildingButtonActionPerformed

    private void SporiBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SporiBuildingButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSporiBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SporiBuildingButtonActionPerformed

    private void ClarkeBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClarkeBuildingButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToClarkBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_ClarkeBuildingButtonActionPerformed

    private void NewFongsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFongsButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToNewFongs();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_NewFongsButtonActionPerformed

    private void BrooklynButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrooklynButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBrooklyn();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BrooklynButtonActionPerformed

    private void BunkhouseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BunkhouseButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToBunkhouse();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_BunkhouseButtonActionPerformed

    private void AlleywayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlleywayButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToAlleyway();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_AlleywayButtonActionPerformed

    private void LibraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToLibrary();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_LibraryButtonActionPerformed

    private void SmithBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmithBuildingButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSmithBuilding();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SmithBuildingButtonActionPerformed

    private void NorthDormsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthDormsButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToNorthDorms();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_NorthDormsButtonActionPerformed

    private void TacoBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TacoBusButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToTacoBus();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_TacoBusButtonActionPerformed

    private void SubwayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubwayButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSubway();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SubwayButtonActionPerformed

    private void ShakeOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShakeOutButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToShakeOut();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_ShakeOutButtonActionPerformed

    private void ICenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICenterButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToICenter();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_ICenterButtonActionPerformed

    private void MCWestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCWestButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToMCWest();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_MCWestButtonActionPerformed

    private void MCEastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCEastButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToMCEast();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_MCEastButtonActionPerformed

    private void SouthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthButtonActionPerformed
        // TODO add your handling code here:
        MapControl.moveToSouthDorms();
        FrameSceneControl.decideFrameExplorePossibility();
        this.dispose();
    }//GEN-LAST:event_SouthButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbandonedHouseOneButton;
    private javax.swing.JButton AbandonedHouseThreeButton;
    private javax.swing.JButton AbandonedHouseTwoButton;
    private javax.swing.JButton AlleywayButton;
    private javax.swing.JButton BikeStoreButton;
    private javax.swing.JButton BirchwoodEastButton;
    private javax.swing.JButton BirchwoodWestButton;
    private javax.swing.JButton BrooklynButton;
    private javax.swing.JButton BroulimsButton;
    private javax.swing.JButton BunkhouseButton;
    private javax.swing.JButton ClarkeBuildingButton;
    private javax.swing.JButton ConstructionButton;
    private javax.swing.JButton CrestwoodButton;
    private javax.swing.JButton DominosButton;
    private javax.swing.JButton DonutsButton;
    private javax.swing.JButton EmptyFieldButton;
    private javax.swing.JButton EmptyLotButton;
    private javax.swing.JButton ExitMap;
    private javax.swing.JButton EyeDoctorButton;
    private javax.swing.JButton FireDeptButton;
    private javax.swing.JButton GringosButton;
    private javax.swing.JButton GunStoreButton;
    private javax.swing.JButton HartBuildingButton;
    private javax.swing.JButton ICenterButton;
    private javax.swing.JButton InsuranceButton;
    private javax.swing.JButton JambaJuiceButton;
    private javax.swing.JButton KeyBankButton;
    private javax.swing.JButton KirkhamButton;
    private javax.swing.JButton KiwiLocoButton;
    private javax.swing.JButton LaJollaButton;
    private javax.swing.JButton LibraryButton;
    private javax.swing.JButton LittleCeasersButton;
    private javax.swing.JButton MCEastButton;
    private javax.swing.JButton MCWestButton;
    private javax.swing.JButton MaverikButton;
    private javax.swing.JButton MelaleucaButton;
    private javax.swing.JButton NewFongsButton;
    private javax.swing.JButton NielsensButton;
    private javax.swing.JButton NorthDormsButton;
    private javax.swing.JButton PinnacleButton;
    private javax.swing.JButton PorterParkFieldButton;
    private javax.swing.JButton PorterParkPlaygroundButton;
    private javax.swing.JButton PostOfficeButton;
    private javax.swing.JButton RoyalCrestButton;
    private javax.swing.JButton SalonButton;
    private javax.swing.JButton ShakeOutButton;
    private javax.swing.JButton SmithBuildingButton;
    private javax.swing.JButton SnowBuildingButton;
    private javax.swing.JButton SouthButton;
    private javax.swing.JButton SporiBuildingButton;
    private javax.swing.JButton StadiumButton;
    private javax.swing.JButton SubwayButton;
    private javax.swing.JButton TacoBellButton;
    private javax.swing.JButton TacoBusButton;
    private javax.swing.JButton TacoTimeButton;
    private javax.swing.JButton VikingVillageButton;
    private javax.swing.JButton WillowsButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
