/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.surviveRexburg.sceneFrames;

import Survivrexburg.SurviveRexburg;
import byui.cit260.survivRexburg.control.GameControl;
import byui.cit260.surviveRexburg.frames.GameMenuFrame;
import byui.cit260.surviveRexburg.frames.MapFrame;

/**
 *
 * @author carissa888
 */
public class startDayFrame extends javax.swing.JFrame {

    /**
     * Creates new form startDayFrame
     */
    public startDayFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        ExploreRexburg = new javax.swing.JRadioButton();
        FortifyButton = new javax.swing.JRadioButton();
        ScavengeButton = new javax.swing.JRadioButton();
        DoNothingButton = new javax.swing.JRadioButton();
        HealthDisplay = new javax.swing.JLabel();
        HungerDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("28 Days Later", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Survive Rexburg");

        jLabel2.setFont(new java.awt.Font("28 Days Later", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DAY " +SurviveRexburg.getCurrentGame().getDaysPassed());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("What do you want to do today?");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("     Enter    ");

        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        ExploreRexburg.setText("Explore Rexburg");
        ExploreRexburg.setToolTipText("");
        ExploreRexburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExploreRexburgActionPerformed(evt);
            }
        });

        FortifyButton.setText("Fortify Location");
        FortifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FortifyButtonActionPerformed(evt);
            }
        });

        ScavengeButton.setText("Scavenge Area");
        ScavengeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScavengeButtonActionPerformed(evt);
            }
        });

        DoNothingButton.setText("Sit and Wait");
        DoNothingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoNothingButtonActionPerformed(evt);
            }
        });

        HealthDisplay.setText("Health: " + SurviveRexburg.getCurrentGame().getEndUser().getHealth());
        HealthDisplay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                HealthDisplayComponentShown(evt);
            }
        });

        HungerDisplay.setText("Hunger: " + SurviveRexburg.getCurrentGame().getEndUser().getHunger());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FortifyButton)
                                    .addComponent(ExploreRexburg)
                                    .addComponent(ScavengeButton)
                                    .addComponent(DoNothingButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(104, 104, 104)
                                .addComponent(MenuButton))
                            .addComponent(jScrollPane1))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(HealthDisplay)
                .addGap(104, 104, 104)
                .addComponent(HungerDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HealthDisplay)
                    .addComponent(HungerDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExploreRexburg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FortifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScavengeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoNothingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuButton)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExploreRexburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExploreRexburgActionPerformed
        // TODO add your handling code here:
        System.out.println("****Explore choice****");
        MapFrame mapFrame = new MapFrame();
        mapFrame.setVisible(true);
    }//GEN-LAST:event_ExploreRexburgActionPerformed

    private void FortifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FortifyButtonActionPerformed
        // TODO add your handling code here:
        GameControl.increaseFortifyLevel();
        System.out.println("**** Fortify choice ****");
        FortifiedLocation fortifiedLocation = new FortifiedLocation();
        fortifiedLocation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FortifyButtonActionPerformed

    private void DoNothingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoNothingButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("**** DoNothing choice ****");
        SurviveRexburg.getFrameSceneControl().decideFrameDoNothingPossibility();
        this.dispose();
    }//GEN-LAST:event_DoNothingButtonActionPerformed

    private void ScavengeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScavengeButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("**** Scavenge choice ****");
        SurviveRexburg.getFrameSceneControl().decideFrameScavengePossibility();
        this.dispose();
    }//GEN-LAST:event_ScavengeButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("****Open Game Menu****");
        GameMenuFrame gameMenu = new GameMenuFrame();
        gameMenu.setVisible(true);
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void HealthDisplayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_HealthDisplayComponentShown
        // TODO add your handling code here:
        System.out.println("***get health****");
        int health = (SurviveRexburg.getEndUser().getHealth()) - 3;
        setTitle("Health - " + health);
    }//GEN-LAST:event_HealthDisplayComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startDayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startDayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startDayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startDayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startDayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DoNothingButton;
    private javax.swing.JRadioButton ExploreRexburg;
    private javax.swing.JRadioButton FortifyButton;
    private javax.swing.JLabel HealthDisplay;
    private javax.swing.JLabel HungerDisplay;
    private javax.swing.JButton MenuButton;
    private javax.swing.JRadioButton ScavengeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
